### ISSUE TITLE
Carbon Intensity explanation

### ISSUE THREAD

**Issue by davehowell** [GreenAlgorithms/green-algorithms-tool#11]
Great project, I love that this exists.

As an Australian the first thing that horrifies me is this 😱 
> the same algorithm will emit 74 times more CO2e if ran in Australia compared to Switzerland

It is explained more here:

> The Carbon Intensity depends on the location and the technologies used to produce electricity. But note that the "energy needed" indicated at the top of this page is independent of the location.

**_The page would benefit from fleshing out exactly why Australia performs so poorly and Switzerland so well._** 

It makes sense that the technology used has an impact - fossil fuels vs clean tech - but why the location? I assume Australia rates so poorly because you are assuming the electricity generation technology is all from gas or coal-fired power stations, is that correct?  Is the location an issue because Switzerland can benefit from free cooling from permafrost or snow-melt, is that the only reason? I'd love to see the calculation for the carbon intensity value.

Australia has one of the highest solar panel installation rates in the world - I have 5KW installed on my own roof so - ignoring the CO2e from the mining/manufacturing/logistics of those panels - running an algorithm on my own machine is essentially free - 0 gCO2e. Some of the cloud providers are generating their own renewable energy. On-grid storage including pumped hydro, compressed air, flywheel, flow-cell, as well as home battery storage is being installed at a rapid rate. The grid is morphing into a distributed collection of smart micro-grids that can buffer and redistribute the huge variations in energy both removed and added to the grid.

We Australians certainly have horrendous carbon footprints, and lack of (National) political leadership, but in spite of that the grassroots changes are happening. Sydney City is taking huge steps https://news.cityofsydney.nsw.gov.au/articles/net-zero-by-2035-city-sydney-bold-new-plan The ACT - the territory containing Canberra, the capital city of Australia - runs on 100% renewable energy https://www.sbs.com.au/news/the-act-is-now-running-on-100-renewable-electricity

**Comment by Llannelongue** [comment]
Hi David, thanks for your message! 

The difference is indeed in electricity production methods (coal vs nuclear and renewable for example), and of course we rely on averages and assume servers are connected to the local power grid.

To see live where the differences between countries come from, check out this map: https://www.electricitymap.org/map  
The carbon intensity we use for Australia is largely from this resource: https://www.carbonfootprint.com/docs/2020_07_emissions_factors_sources_for_2020_electricity_v1_3.pdf 
As this is largely based on national energy mix data released by each government, there is a delay between the implementation of new policies, and the updated carbon intensities.

We are looking at adding the option of inputing custom carbon intensities, and hopefully this will be in next releases of the app. For now, if you want to use a custom CI, you can select a country with a CI close to yours to get a reasonable estimate.
