### ISSUE TITLE
Calculation gap

### ISSUE THREAD

**Issue by Geodouss** [GreenAlgorithms/green-algorithms-tool#15]
Hi gang
First of all, thanks for the amazing piece of work.
I have tried to create an excel model re-using the algorythm used to estimate the energy required and the associated Carbon footprint.
I have tried many thing but always have a delta between the website output and my excel output attached. 
With the parameters below, I get 5.77 kWh in my excel vs 4.56 kWh on the website.
I have tried many times and am not able to find out why. Are there other parameters that I should factor in?
 
Runtime - 24
Number of cores - 12
Model - Xeon E5-2683 V4
Memory available (GB) - 64
Local server in Autria - Europe

[Computing Carbon Footprint tool_0.1.xlsx](https://github.com/GreenAlgorithms/green-algorithms-tool/files/7514374/Computing.Carbon.Footprint.tool_0.1.xlsx)

**Comment by Llannelongue** [comment]
Hi @Geodouss, thanks for your patience! I'm not sure where the difference comes from without seeing your calculations, but I've redone the calculation on Excel, hope that helps!

(Note that location doesn't matter for the power usage)

![image](https://user-images.githubusercontent.com/22586038/145393670-c7be3107-3f8a-42e2-805f-148b9c546015.png)

**Comment by Llannelongue** [comment]
Actually I missed your attachment! I've found the error: you use 10W/core while it's actually 7.5 W/core (TDP=120W, and there are 16 cores) 😃
