### ISSUE TITLE
Add perma-link to results

### ISSUE THREAD

**Issue by manics** [GreenAlgorithms/green-algorithms-tool#6]
Thanks for a great #biodata20 talk! I think it'd be nice if the dashboard could provide a perma-link so people can share their results, e.g. something like `https://www.green-algorithms.org/?runtime=24&cpu=2&...`. If you're worried about long-term support of links when you make changes you could perhaps install the app under a `/version` prefix?

**Comment by Llannelongue** [comment]
Thanks for the suggestion! It took a while to have that implemented (it was a real pain to do!), but the permalinks are now up and running in the v2.0! Feel free to test it and let us know if you find any bugs :)

**Comment by manics** [comment]
Thanks for adding this, it's working well!
